import React, { Fragment, ReactElement } from "react";
import type { AppProps } from "next/app";
import Head from "next/head";
import { NextPage } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.scss";

export type NextPageWithLayout = NextPage & {
	Layout?: (props: any) => ReactElement;
};

export type AppPropsWithLayout = AppProps & {
	Component: NextPageWithLayout;
};

const App = ({ Component, pageProps }: AppPropsWithLayout) => {
	const Layout = Component.Layout ?? Fragment;

	return (
		<div className="root-app">
			<Head>
				<title>Demo Nextjs</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Component {...pageProps} />
			</Layout>
		</div>
	);
};

export default App;
